# Agenda
* Numpy
* Pandas
* Lab


# Introduction


## Create a new notebook for your code-along:

From our submission directory, type:
    
    jupyter notebook

From the IPython Dashboard, open a new notebook.
Change the title to: "Numpy and Pandas"

# Introduction to Numpy

* Overview
* ndarray
* Indexing and Slicing

More info: [http://wiki.scipy.org/Tentative_NumPy_Tutorial](http://wiki.scipy.org/Tentative_NumPy_Tutorial)


## Numpy Overview

* Why Python for Data? Numpy brings *decades* of C math into Python!
* Numpy provides a wrapper for extensive C/C++/Fortran codebases, used for data analysis functionality
* NDAarray allows easy vectorized math and broadcasting (i.e. functions for vector elements of different shapes)

In [1]:
import numpy as np

### Creating ndarrays

An array object represents a multidimensional, homogeneous array of fixed-size items. 

In [2]:
# Creating arrays
a = np.zeros((3))
b = np.ones((2,3))
c = np.random.randint(1,10,(2,3,4))
d = np.arange(0,11,1)

What are these functions?

    arange?

In [3]:
# Note the way each array is printed:
a,b,c,d

(array([ 0.,  0.,  0.]), array([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.]]), array([[[7, 4, 4, 6],
         [6, 6, 3, 9],
         [6, 7, 7, 2]],
 
        [[8, 9, 9, 2],
         [5, 6, 5, 4],
         [8, 1, 2, 4]]]), array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10]))

In [ ]:
## Arithmetic in arrays is element wise

In [4]:
a = np.array( [20,30,40,50] )
b = np.arange( 4 )
b

array([0, 1, 2, 3])

In [5]:
c = a-b
c

array([20, 29, 38, 47])

In [6]:
b**2

array([0, 1, 4, 9])

## Indexing, Slicing and Iterating

In [7]:
# one-dimensional arrays work like lists:
a = np.arange(10)**2

In [8]:
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [9]:
a[2:5]

array([ 4,  9, 16])

In [ ]:
# Multidimensional arrays use tuples with commas for indexing
# with (row,column) conventions beginning, as always in Python, from 0

In [10]:
b = np.random.randint(1,100,(4,4))

In [11]:
b

array([[54, 78, 87, 94],
       [49, 62, 89, 54],
       [73, 36, 66, 26],
       [58, 72, 34,  2]])

In [12]:
# Guess the output
print(b[2,3])
print(b[0,0])


26
54


In [13]:
b[0:3,1],b[:,1]

(array([78, 62, 36]), array([78, 62, 36, 72]))

In [14]:
b[1:3,:]

array([[49, 62, 89, 54],
       [73, 36, 66, 26]])

# Introduction to Pandas

* Object Creation
* Viewing data
* Selection
* Missing data
* Grouping
* Reshaping
* Time series
* Plotting
* i/o
 

_pandas.pydata.org_

## Pandas Overview

_Source: [pandas.pydata.org](http://pandas.pydata.org/pandas-docs/stable/10min.html)_

In [15]:
import pandas as pd
import numpy as np

In [16]:
dates = pd.date_range('20140101',periods=6)
dates

DatetimeIndex(['2014-01-01', '2014-01-02', '2014-01-03', '2014-01-04',
               '2014-01-05', '2014-01-06'],
              dtype='datetime64[ns]', freq='D')

In [17]:
df = pd.DataFrame(np.random.randn(6,4),index=dates,columns=list('ABCD'))
z = pd.DataFrame(index = df.index, columns = df.columns)
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [18]:
# Index, columns, underlying numpy data
df

A         B         C         D
2014-01-01 -0.332955 -0.469883  0.069069  1.284538
2014-01-02 -0.403104  0.343110 -0.050504  0.863697
2014-01-03  0.113261  0.255686  0.173524  0.420273
2014-01-04  0.839918  0.255643  1.515153 -0.194768
2014-01-05  0.338414  0.858056 -0.793311  0.715983
2014-01-06 -1.276778 -0.300923 -0.654213  1.080297

In [19]:
z

A    B    C    D
2014-01-01  NaN  NaN  NaN  NaN
2014-01-02  NaN  NaN  NaN  NaN
2014-01-03  NaN  NaN  NaN  NaN
2014-01-04  NaN  NaN  NaN  NaN
2014-01-05  NaN  NaN  NaN  NaN
2014-01-06  NaN  NaN  NaN  NaN

In [20]:
df2 = pd.DataFrame({ 'A' : 1.,
                         'B' : pd.Timestamp('20130102'),
                         'C' : pd.Series(1,index=list(range(4)),dtype='float32'),
                         'D' : np.array([3] * 4,dtype='int32'),
                         'E' : 'foo' })
    

df2

A          B    C  D    E
0  1.0 2013-01-02  1.0  3  foo
1  1.0 2013-01-02  1.0  3  foo
2  1.0 2013-01-02  1.0  3  foo
3  1.0 2013-01-02  1.0  3  foo

In [8]:
# With specific dtypes
df2.dtypes

A           float64
B    datetime64[ns]
C           float32
D             int32
E            object
dtype: object

#### Viewing Data

In [26]:
df.head()

A         B         C         D
2014-01-01 -0.332955 -0.469883  0.069069  1.284538
2014-01-02 -0.403104  0.343110 -0.050504  0.863697
2014-01-03  0.113261  0.255686  0.173524  0.420273
2014-01-04  0.839918  0.255643  1.515153 -0.194768
2014-01-05  0.338414  0.858056 -0.793311  0.715983

In [27]:
df.tail()

A         B         C         D
2014-01-02 -0.403104  0.343110 -0.050504  0.863697
2014-01-03  0.113261  0.255686  0.173524  0.420273
2014-01-04  0.839918  0.255643  1.515153 -0.194768
2014-01-05  0.338414  0.858056 -0.793311  0.715983
2014-01-06 -1.276778 -0.300923 -0.654213  1.080297

In [21]:
df.index

DatetimeIndex(['2014-01-01', '2014-01-02', '2014-01-03', '2014-01-04',
               '2014-01-05', '2014-01-06'],
              dtype='datetime64[ns]', freq='D')

In [22]:
df.describe()

A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean  -0.120207  0.156948  0.043286  0.695003
std    0.727960  0.479221  0.822097  0.527649
min   -1.276778 -0.469883 -0.793311 -0.194768
25%   -0.385567 -0.161782 -0.503286  0.494201
50%   -0.109847  0.255664  0.009282  0.789840
75%    0.282126  0.321254  0.147410  1.026147
max    0.839918  0.858056  1.515153  1.284538

In [23]:
df.sort_values(by='B', axis=0)

A         B         C         D
2014-01-01 -0.332955 -0.469883  0.069069  1.284538
2014-01-06 -1.276778 -0.300923 -0.654213  1.080297
2014-01-04  0.839918  0.255643  1.515153 -0.194768
2014-01-03  0.113261  0.255686  0.173524  0.420273
2014-01-02 -0.403104  0.343110 -0.050504  0.863697
2014-01-05  0.338414  0.858056 -0.793311  0.715983

### Selection

In [24]:
df[['A','B']]

A         B
2014-01-01 -0.332955 -0.469883
2014-01-02 -0.403104  0.343110
2014-01-03  0.113261  0.255686
2014-01-04  0.839918  0.255643
2014-01-05  0.338414  0.858056
2014-01-06 -1.276778 -0.300923

In [28]:
df.iloc[1]

A   -0.403104
B    0.343110
C   -0.050504
D    0.863697
Name: 2014-01-02 00:00:00, dtype: float64

In [29]:
# By label
df.loc[dates[0]]

A   -0.332955
B   -0.469883
C    0.069069
D    1.284538
Name: 2014-01-01 00:00:00, dtype: float64

In [30]:
# multi-axis by label
df.loc[:,['A','B']]

A         B
2014-01-01 -0.332955 -0.469883
2014-01-02 -0.403104  0.343110
2014-01-03  0.113261  0.255686
2014-01-04  0.839918  0.255643
2014-01-05  0.338414  0.858056
2014-01-06 -1.276778 -0.300923

In [31]:
# Date Range
df.loc['20140102':'20140104',['B']]

B
2014-01-02  0.343110
2014-01-03  0.255686
2014-01-04  0.255643

In [32]:
# iloc provides integer locations similar to np style
df.iloc[3:]

A         B         C         D
2014-01-04  0.839918  0.255643  1.515153 -0.194768
2014-01-05  0.338414  0.858056 -0.793311  0.715983
2014-01-06 -1.276778 -0.300923 -0.654213  1.080297

In [33]:
df[1:2]

A        B         C         D
2014-01-02 -0.403104  0.34311 -0.050504  0.863697

### Boolean Indexing

In [37]:
df[df.A < 0][['A', 'B']] # Basically a 'where' operation

A         B
2014-01-01 -0.332955 -0.469883
2014-01-02 -0.403104  0.343110
2014-01-06 -1.276778 -0.300923

### Setting

In [38]:
df_posA = df.copy() # Without "copy" it would act on the dataset

df_posA[df_posA.A < 0] = -1*df_posA

In [39]:
df_posA

A         B         C         D
2014-01-01  0.332955  0.469883 -0.069069 -1.284538
2014-01-02  0.403104 -0.343110  0.050504 -0.863697
2014-01-03  0.113261  0.255686  0.173524  0.420273
2014-01-04  0.839918  0.255643  1.515153 -0.194768
2014-01-05  0.338414  0.858056 -0.793311  0.715983
2014-01-06  1.276778  0.300923  0.654213 -1.080297

In [40]:
#Setting new column aligns data by index
s1 = pd.Series([1,2,3,4,5,6],index=pd.date_range('20140102',periods=6))

In [41]:
s1

2014-01-02    1
2014-01-03    2
2014-01-04    3
2014-01-05    4
2014-01-06    5
2014-01-07    6
Freq: D, dtype: int64

In [42]:
df['F'] = s1

In [43]:
df

A         B         C         D    F
2014-01-01 -0.332955 -0.469883  0.069069  1.284538  NaN
2014-01-02 -0.403104  0.343110 -0.050504  0.863697  1.0
2014-01-03  0.113261  0.255686  0.173524  0.420273  2.0
2014-01-04  0.839918  0.255643  1.515153 -0.194768  3.0
2014-01-05  0.338414  0.858056 -0.793311  0.715983  4.0
2014-01-06 -1.276778 -0.300923 -0.654213  1.080297  5.0

### Missing Data

In [44]:
# Add a column with missing data
df1 = df.reindex(index=dates[0:4],columns=list(df.columns) + ['E'])

In [45]:
df1.loc[dates[0]:dates[1],'E'] = 1

In [46]:
df1

A         B         C         D    F    E
2014-01-01 -0.332955 -0.469883  0.069069  1.284538  NaN  1.0
2014-01-02 -0.403104  0.343110 -0.050504  0.863697  1.0  1.0
2014-01-03  0.113261  0.255686  0.173524  0.420273  2.0  NaN
2014-01-04  0.839918  0.255643  1.515153 -0.194768  3.0  NaN

In [47]:
# find where values are null
pd.isnull(df1)

A      B      C      D      F      E
2014-01-01  False  False  False  False   True  False
2014-01-02  False  False  False  False  False  False
2014-01-03  False  False  False  False  False   True
2014-01-04  False  False  False  False  False   True

### Operations

In [48]:
df.describe()

A         B         C         D         F
count  6.000000  6.000000  6.000000  6.000000  5.000000
mean  -0.120207  0.156948  0.043286  0.695003  3.000000
std    0.727960  0.479221  0.822097  0.527649  1.581139
min   -1.276778 -0.469883 -0.793311 -0.194768  1.000000
25%   -0.385567 -0.161782 -0.503286  0.494201  2.000000
50%   -0.109847  0.255664  0.009282  0.789840  3.000000
75%    0.282126  0.321254  0.147410  1.026147  4.000000
max    0.839918  0.858056  1.515153  1.284538  5.000000

In [49]:
df.mean(),df.mean(1) # Operation on two different axes

(A   -0.120207
 B    0.156948
 C    0.043286
 D    0.695003
 F    3.000000
 dtype: float64, 2014-01-01    0.137692
 2014-01-02    0.350640
 2014-01-03    0.592549
 2014-01-04    1.083189
 2014-01-05    1.023828
 2014-01-06    0.769677
 Freq: D, dtype: float64)

In [50]:
a = [True, False]

In [51]:
df1.mean(axis=1)

2014-01-01    0.310154
2014-01-02    0.458866
2014-01-03    0.592549
2014-01-04    1.083189
Freq: D, dtype: float64

In [52]:
df3 = pd.isnull(df1)

In [53]:
df3

A      B      C      D      F      E
2014-01-01  False  False  False  False   True  False
2014-01-02  False  False  False  False  False  False
2014-01-03  False  False  False  False  False   True
2014-01-04  False  False  False  False  False   True

In [54]:
df3.mean()

A    0.00
B    0.00
C    0.00
D    0.00
F    0.25
E    0.50
dtype: float64

### I/O
I/O is straightforward with, for example, pd.read_csv or df.to_csv

#### The benefits of open source:

Let's look under x's in plt modules

# Next Steps

**Recommended Resources**

Name | Description
--- | ---
[Official Pandas Tutorials](http://pandas.pydata.org/pandas-docs/stable/10min.html) | Wes & Company's selection of tutorials and lectures
[Julia Evans Pandas Cookbook](https://github.com/jvns/pandas-cookbook) | Great resource with examples from weather, bikes and 311 calls
[Learn Pandas Tutorials](https://bitbucket.org/hrojas/learn-pandas) | A great series of Pandas tutorials from Dave Rojas
[Research Computing Python Data PYNBs](https://github.com/ResearchComputing/Meetup-Fall-2013/tree/master/python) | A super awesome set of python notebooks from a meetup-based course exclusively devoted to pandas